crontabui:
  enabled: true
  image:
    repository: highcanfly/crontab-ui
    tag: latest
  resources:
    limits:
      cpu: 250m
      memory: "214748364"
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  replicas: 1
  type: ClusterIP
dolidock:
  doliDbHost: mysql
  doliDbHostPort: "3306"
  doliDbType: mysqli
  doliUrlRoot: https://dolidock.example.org
  allowedSenderDomains: ""
  apiLayerKey: ""
  cloudflareApiKey: ""
  cloudflareDnsRecords: ""
  cloudflareZoneId: ""
  crontabuiPassword: ""
  crontabuiUser: "administrator"
  dkimPrivateKey: ""
  dkimSelector: "dkim-dolidock"
  doliAdminLogin: "administrator"
  doliAdminPassword: ""
  doliDbName: "dolidock"
  doliDbPassword: ""
  doliDbUser: "dbuser"
  doliDbPrefix: llx_
  mysqlRootPassword: ""
  postfixHostname: ""
  hostname: ""
  adminHostname: ""
  crontabuiHostname: ""
  backupFrom: ""
  backupTo: ""
  wwwGroupId: "1000"
  wwwUserId: "1000"
  image:
    repository: ismogroup/dolidock
    tag: latest
  resources:
    limits:
      cpu: "1"
      memory: 3Gi
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  replicas: 1
  type: ClusterIP
dolirate:
  mysqlHost: mysql
  mysqlPort: "3306"
  image:
    repository: ismogroup/dolirate
    tag: latest
  resources:
    limits:
      cpu: 250m
      memory: 100M
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  replicas: 1
  type: ClusterIP
imagePullSecrets: []
kubernetesClusterDomain: cluster.local
memcached:
  image:
    repository: memcached
    tag: alpine
  resources:
    limits:
      cpu: 250m
      memory: 1Gi
  ports:
  - name: "11211"
    port: 11211
    targetPort: 11211
  replicas: 1
  type: ClusterIP
mysql:
  image:
    repository: mysql
    tag: latest
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  replicas: 1
  type: ClusterIP
phpmyadmin:
  pmaHost: mysql
  image:
    repository: phpmyadmin
    tag: latest
  resources:
    limits:
      cpu: 250m
      memory: 512M
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  replicas: 1
  type: ClusterIP
pvc:
  crontabuiData:
    storageRequest: 1Gi
  dolidockData:
    storageRequest: 3Gi
  mysqlData:
    storageRequest: 1Gi
  smtpdData:
    storageRequest: 25Mi
smtpd:
  updateStrategy: RollingUpdate # Recreate | RollingUpdate
  useDolidockPVC: false
  useCloudflareDDNS: "0"
  useLetsEncrypt: "0"
  relayHost: ""
  ports:
  - name: "25"
    port: 25
    targetPort: 25
  replicas: 1
  image:
    repository: highcanfly/smtp-relay
    tag: latest
  resources:
    limits:
      cpu: 900m
      memory: "322122547"
  type: ClusterIP
ingress:
  ingressClassName: nginx
  tls:
    certIssuer: ""