{{ if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mailtrain-public
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ if .Values.ingress.clusterIssuer -}}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    {{ end -}}
    {{ if .Values.ingress.annotations -}}
    {{ .Values.ingress.annotations | toYaml | nindent 4}}
    {{ end -}}
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.app.HOST_BASE_PUBLIC }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.app.HOST_BASE_PUBLIC }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: mailtrain      
              port: 
                number: {{ .Values.service.publicPort }}
  {{ if .Values.ingress.clusterIssuer -}}
  tls:
  - hosts: [{{ .Values.app.HOST_BASE_PUBLIC }}]
    secretName: mailtrain-public-tls-cert
  {{ end }}
{{ end }}