{{- if and .Values.storage.persistence.enabled (not .Values.storage.kvdata.existingClaim) .Values.storage.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: mailtrain-kvdata
  name: {{ .Values.storage.kvdata.claimName }}
spec:
  accessModes: {{ .Values.storage.kvdata.accessModes | toYaml | nindent 4 }}
  {{- if .Values.storage.kvdata.storageClassName }}
  storageClassName: {{ .Values.storage.kvdata.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.kvdata.size }}
  volumeMode: Filesystem
status: {}
{{- end }}
