
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
type: Opaque
data:
  {{- if not .Values.app.MYSQL_ROOT_PASSWORD}}
  MYSQL_ROOT_PASSWORD: {{ randAlphaNum 12 | b64enc }}
  {{- else }}
  MYSQL_ROOT_PASSWORD: {{ .Values.app.MYSQL_ROOT_PASSWORD | b64enc }}
  {{- end }}
  {{- if not .Values.app.MYSQL_PASSWORD}}
  MYSQL_PASSWORD: {{ randAlphaNum 12 | b64enc }}
  {{- else }}
  MYSQL_PASSWORD: {{ .Values.app.MYSQL_PASSWORD| b64enc }}
  {{- end }}
