apiVersion: v1
kind: Secret
metadata:
  name: mailtrain
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mailtrain
    app.kubernetes.io/instance: mailtrain
type: Opaque
data:
  {{- if not .Values.app.ADMIN_PASSWORD }}
  ADMIN_PASSWORD: {{ randAlphaNum 12 | b64enc }}
  {{- else }}
  ADMIN_PASSWORD: {{ .Values.app.ADMIN_PASSWORD | b64enc  }}
  {{- end }}
  CLOUDFLARE_API_KEY: {{ .Values.cloudflare.apiKey | b64enc }}
  CLOUDFLARE_ZONE_ID: {{ .Values.cloudflare.zoneId | b64enc }}
  CLOUDFLARE_DNS_RECORDS: {{ .Values.cloudflare.dnsRecord | first | b64enc }}
  BACKUP_TO: {{ .Values.backup.to | b64enc }}
  BACKUP_FROM: {{ .Values.backup.from | b64enc }}
