{{- $mysqlSecret := (lookup "v1" "Secret" .Release.Namespace "mysql") -}}
{{ if not $mysqlSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/instance: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ randAlphaNum 12 | b64enc }}
  MYSQL_PASSWORD: {{ randAlphaNum 12 | b64enc }}
{{ end }}


{{- $mailtrainlSecret := (lookup "v1" "Secret" .Release.Namespace "mailtrain") -}}
{{ if not $mailtrainlSecret -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: mailtrain
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mailtrain
    app.kubernetes.io/instance: mailtrain
type: Opaque
data:
  ADMIN_PASSWORD: {{ randAlphaNum 12 | b64enc }}
  CLOUDFLARE_API_KEY: {{ .Values.cloudflare.apiKey | b64enc }}
  CLOUDFLARE_ZONE_ID: {{ .Values.cloudflare.zoneId | b64enc }}
  CLOUDFLARE_DNS_RECORDS: {{ .Values.cloudflare.dnsRecord | first | b64enc }}
  BACKUP_TO: {{ .Values.backup.to | b64enc }}
  BACKUP_FROM: {{ .Values.backup.from | b64enc }}
{{ end }}