
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.storage.kvdata.redisPort | quote }}
      port: {{ .Values.storage.kvdata.redisPort }}
      targetPort: {{ .Values.storage.kvdata.redisPort }}
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}
