apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.storage.kvdata.mongoPort | quote }}
      port: {{ .Values.storage.kvdata.mongoPort }}
      targetPort: {{ .Values.storage.kvdata.mongoPort }}
  selector:
    io.kompose.service: mongo
status:
  loadBalancer: {}
