---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mysql
  name: mysql
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.storage.mysql.port | quote }}
      port: {{ .Values.storage.mysql.port }}
      targetPort: {{ .Values.storage.mysql.port }}
  selector:
    io.kompose.service: mysql
status:
  loadBalancer: {}
