---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mysql
  name: mysql
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.storage.mysql.port | quote }}
      port: {{ .Values.storage.mysql.port }}
      targetPort: {{ .Values.storage.mysql.port }}
  selector:
    io.kompose.service: mysql
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.storage.kvdata.redisPort | quote }}
      port: {{ .Values.storage.kvdata.redisPort }}
      targetPort: {{ .Values.storage.kvdata.redisPort }}
  selector:
    io.kompose.service: redis
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mongo
  name: mongo
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.storage.kvdata.mongoPort | quote }}
      port: {{ .Values.storage.kvdata.mongoPort }}
      targetPort: {{ .Values.storage.kvdata.mongoPort }}
  selector:
    io.kompose.service: mongo
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: mailtrain
  name: mailtrain
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.service.basePort | quote }}
      port: {{ .Values.service.basePort }}
      targetPort: {{ .Values.service.basePort }}
    - name: {{ .Values.service.sandboxPort | quote }}
      port: {{ .Values.service.sandboxPort }}
      targetPort: {{ .Values.service.sandboxPort }}
    - name: {{ .Values.service.publicPort | quote }}
      port: {{ .Values.service.publicPort }}
      targetPort: {{ .Values.service.publicPort }}
  selector:
    io.kompose.service: mailtrain
status:
  loadBalancer: {}

---
{{ if .Values.phpmyadmin.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: phpmyadmin
  name: phpmyadmin
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Values.phpmyadmin.port | quote }}
      port: {{ .Values.phpmyadmin.port }}
      targetPort: {{ .Values.phpmyadmin.port }}
  selector:
    io.kompose.service: phpmyadmin
status:
  loadBalancer: {}
{{ end }}