{{- if .Values.proxy.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ollama.fullname" . }}-proxy-keys
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
    app: {{ include "ollama.name" . }}-proxy
type: Opaque
data:
  keys.txt: {{ .Values.proxy.apiKeys | join "\n" | b64enc | quote }}
{{- end -}}
