{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "ollama.name" .) .Values.serviceAccount.name }}
  labels:
    {{- include "ollama.labels" . | nindent 4 }}
{{- end }}
