apiVersion: v1
kind: Service
metadata:
  name: {{ include "hcfmailer.fullname" . }}-hcfmailer
  labels:
    io.kompose.service: hcfmailer
  {{- include "hcfmailer.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o okteto/k8s.yml
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.hcfmailer.type }}
  selector:
    io.kompose.service: hcfmailer
  {{- include "hcfmailer.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.hcfmailer.ports | toYaml | nindent 2 -}}