apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hcfmailer.fullname" . }}-hcfmailing-uploads
  labels:
    io.kompose.service: hcfmailing-uploads
  {{- include "hcfmailer.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.hcfmailingUploads.storageRequest | quote }}