apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hcfmailer.fullname" . }}-hcfmailing-pgsql
  labels:
    io.kompose.service: hcfmailing-pgsql
  {{- include "hcfmailer.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.hcfmailingPgsql.storageRequest | quote }}
  volumeMode: Filesystem