apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "hcfmailer.fullname" . }}-newsletter
  labels:
  {{- include "hcfmailer.labels" . | nindent 4 }}
spec:
  rules:
  - host: {{ required "listmonk.newsletterFqdnHost is required" .Values.listmonk.newsletterFqdnHost
    | quote }}
    http:
      paths:
      - backend:
          service:
            name: '{{ include "hcfmailer.fullname" . }}-hcfmailer'
            port:
              number: 9000
        path: /
        pathType: Prefix