apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hcfmailer.fullname" . }}-smtpd
  labels:
  {{- include "hcfmailer.labels" . | nindent 4 }}
stringData:
  cloudflare-api_key: {{ required "smtpd.cloudflareApiKey is required" .Values.smtpd.cloudflareApiKey
    | quote }}
  cloudflare-dns-records: {{ required "smtpd.cloudflareDnsRecords is required" .Values.smtpd.cloudflareDnsRecords
    | quote }}
  cloudflare-zone-id: {{ required "smtpd.cloudflareZoneId is required" .Values.smtpd.cloudflareZoneId
    | quote }}
  postfix-hostname: {{ required "smtpd.postfixHostname is required" .Values.smtpd.postfixHostname
    | quote }}
  smtpd-allowed-sender-domains: {{ required "smtpd.smtpdAllowedSenderDomains is required"
    .Values.smtpd.smtpdAllowedSenderDomains | quote }}
  smtpd-dkim-private-key: {{ required "smtpd.smtpdDkimPrivateKey is required" .Values.smtpd.smtpdDkimPrivateKey
    | quote }}
  smtpd-dkim-selector: {{ required "smtpd.smtpdDkimSelector is required" .Values.smtpd.smtpdDkimSelector
    | quote }}
  smtpd-postfix-hotname: {{ required "smtpd.smtpdPostfixHotname is required" .Values.smtpd.smtpdPostfixHotname
    | quote }}
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hcfmailer.fullname" . }}-smtpd
  labels:
    io.kompose.service: smtpd
  {{- include "hcfmailer.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o okteto/k8s.yml
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.smtpd.type }}
  selector:
    io.kompose.service: smtpd
  {{- include "hcfmailer.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.smtpd.ports | toYaml | nindent 2 -}}