#########################################################################
# © Ronan LE MEILLAT 2023
# released under the GPLv3 terms
#########################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: deployment-hcfschedule
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hcfschedule-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hcfschedule-server
    spec:
      containers:
        - env:
            - name: BASE_URL
              value: {{ .Values.deploymentHCFSchedule.baseUrl }}
            - name: LANGUAGE
              value: {{ .Values.deploymentHCFSchedule.language }}
            - name: DEBUG
              value: {{ squote .Values.deploymentHCFSchedule.debug }}
            - name: DB_HOST
              value: {{ .Values.deploymentHCFSchedule.dbhost }}
            - name: DB_NAME
              value: {{ .Values.deploymentHCFSchedule.dbname }}
            - name: DB_USERNAME
              value: {{ .Values.deploymentHCFSchedule.dbusername }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: root
                  name: mysql-credentials
            - name: MAIL_USERAGENT
              value:  {{ .Values.deploymentHCFSchedule.mailUserAgent }}
            - name: MAIL_PROTOCOL
              value:  {{ .Values.deploymentHCFSchedule.mailProtocol }}
            - name: MAIL_TYPE
              value:  {{ .Values.deploymentHCFSchedule.mailType }}
            - name: MAIL_SMTP_DEBUG
              value:  {{ squote .Values.deploymentHCFSchedule.mailSmtpDebug }}
            - name: MAIL_SMTP_AUTH
              value:  {{ squote .Values.deploymentHCFSchedule.mailSmtpAuth }}
            - name: MAIL_SMTP_HOST
              value:  {{ .Values.deploymentHCFSchedule.mailSmtpHost }}
            - name: MAIL_SMTP_USER
              valueFrom:
                secretKeyRef:
                  key: user
                  name: hcfschedule-credentials
            - name: MAIL_SMTP_PASS
              valueFrom:
                secretKeyRef:
                  key: password
                  name: hcfschedule-credentials
            - name: MAIL_SMTP_CRYPTO
              value:  {{ squote .Values.deploymentHCFSchedule.mailSmtpCrypto }}
            - name: MAIL_SMTP_PORT
              value:  {{ squote .Values.deploymentHCFSchedule.mailSmtpPort }}
            - name: GOOGLE_SYNC_FEATURE
              value: {{ squote .Values.deploymentHCFSchedule.googleSync }}
            - name: GOOGLE_PRODUCT_NAME
            - name: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_API_KEY
          image: {{ print .Values.deploymentHCFSchedule.image ":" .Values.deploymentHCFSchedule.imageTag }}
          imagePullPolicy: IfNotPresent
          name: hcfschedule-server
          ports:
            - containerPort: 8888
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 1Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
