#########################################################################
# © Ronan LE MEILLAT 2023
# released under the GPLv3 terms
#########################################################################
apiVersion: v1
kind: Secret
metadata:
  annotations: {}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: hcfschedule-credentials
data:
  user: {{ b64enc .Values.deploymentHCFSchedule.mailSmtpUser }}
  password: {{ b64enc .Values.deploymentHCFSchedule.mailSmtpPass }}
type: Opaque
