#########################################################################
# © Ronan LE MEILLAT 2023
# released under the GPLv3 terms
#########################################################################
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: hcfschedule-service
spec:
  ports:
    - name: hcfschedule-server
      port: {{ .Values.serviceEasyappointment.port }}
      protocol: TCP
      targetPort: {{ .Values.serviceEasyappointment.port }}
  selector:
    app: hcfschedule-server
  sessionAffinity: None
  type: ClusterIP
