apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolidock
  labels:
    io.kompose.service: dolidock
  {{- include "dolidock.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dolidock.replicas }}
  selector:
    matchLabels:
      io.kompose.service: dolidock
    {{- include "dolidock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.network/dolidock-default: "true"
        io.kompose.service: dolidock
      {{- include "dolidock.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: DOLI_ADMIN_LOGIN
          valueFrom:
            secretKeyRef:
              key: DOLI_ADMIN_LOGIN
              name: dolidock
        - name: DOLI_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DOLI_ADMIN_PASSWORD
              name: dolidock
        - name: DOLI_DB_NAME
          valueFrom:
            secretKeyRef:
              key: DOLI_DB_NAME
              name: dolidock
        - name: DOLI_DB_USER
          valueFrom:
            secretKeyRef:
              key: DOLI_DB_USER
              name: dolidock
        - name: DOLI_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DOLI_DB_PASSWORD
              name: dolidock
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: dolidock
        - name: DOLI_DB_TYPE
          value: {{ .Values.dolidock.doliDbType }}
        - name: DOLI_DB_HOST
          value: {{ .Values.dolidock.doliDbHost }}
        - name: DOLI_DB_HOST_PORT
          value: {{ .Values.dolidock.doliDbHostPort | quote }}
        - name: DOLI_URL_ROOT
          value: {{ .Values.dolidock.doliUrlRoot }}
        - name: WWW_USER_ID
          value: {{ .Values.dolidock.wwwUserId | quote }}
        - name: WWW_GROUP_ID
          value: {{ .Values.dolidock.wwwGroupId | quote }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.dolidock.image.repository }}:{{ .Values.dolidock.image.tag
          | default .Chart.AppVersion }}
        name: dolidock
        ports:
        - containerPort: 80
        resources: {{- toYaml .Values.dolidock.resources | nindent 10 }}
        securityContext:
          runAsGroup: 0
          runAsUser: 0
        volumeMounts:
        - mountPath: /var/www/dolidock/documents
          name: dolidock-data
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      restartPolicy: Always
      volumes:
      - name: dolidock-data
        persistentVolumeClaim:
          claimName: dolidock-data