apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolirate
  labels:
    io.kompose.service: dolirate
  {{- include "dolidock.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dolirate.replicas }}
  selector:
    matchLabels:
      io.kompose.service: dolirate
    {{- include "dolidock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.network/dolidock-default: "true"
        io.kompose.service: dolirate
      {{- include "dolidock.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: {{ .Values.dolidock.doliDbHost }}
        - name: MYSQL_PORT
          value: {{ .Values.dolidock.doliDbHostPort | quote }}
        - name: DOLI_DB_USER
          valueFrom:
            secretKeyRef:
              key: DOLI_DB_USER
              name: dolidock
        - name: DOLI_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DOLI_DB_PASSWORD
              name: dolidock
        - name: DOLI_DB_PREFIX
          value: {{ .Values.dolidock.doliDbPrefix }}
        - name: DOLI_DB_NAME
          valueFrom:
            secretKeyRef:
              key: DOLI_DB_NAME
              name: dolidock
        - name: API_LAYER_KEY
          valueFrom:
            secretKeyRef:
              key: API_LAYER_KEY
              name: dolidock
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.dolirate.image.repository }}:{{ .Values.dolirate.image.tag | default .Chart.AppVersion }}
        name: dolirate
        ports:
        - containerPort: 3000
        resources: {{- toYaml .Values.dolirate.resources | nindent 10 }}
        securityContext:
          runAsGroup: 0
          runAsUser: 0
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      restartPolicy: Always