apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtpd
  labels:
    io.kompose.service: smtpd
  {{- include "dolidock.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o okteto/k8s.yml
    kompose.version: 1.28.0 (c4137012e)
spec:
  replicas: {{ .Values.smtpd.replicas }}
  selector:
    matchLabels:
      io.kompose.service: smtpd
    {{- include "dolidock.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.network/dolidock-default: "true"
        io.kompose.service: smtpd
      {{- include "dolidock.selectorLabels" . | nindent 8 }}
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o okteto/k8s.yml
        kompose.version: 1.28.0 (c4137012e)
    spec:
      containers:
      - env:
        - name: ALLOWED_SENDER_DOMAINS
          valueFrom:
            secretKeyRef:
              key: ALLOWED_SENDER_DOMAINS
              name: dolidock
        - name: DKIM_PRIVATE_KEY
          valueFrom:
            secretKeyRef:
              key: DKIM_PRIVATE_KEY
              name: dolidock
        - name: DKIM_SELECTOR
          valueFrom:
            secretKeyRef:
              key: DKIM_SELECTOR
              name: dolidock
        {{ if eq .Values.dolidock.useCloudflareDDNS '1' }}
        - name: CLOUDFLARE_ZONE_ID
          valueFrom:
            secretKeyRef:
              key: CLOUDFLARE_ZONE_ID
              name: dolidock
        - name: CLOUDFLARE_API_KEY
          valueFrom:
            secretKeyRef:
              key: CLOUDFLARE_API_KEY
              name: dolidock
        - name: CLOUDFLARE_DNS_RECORDS
          valueFrom:
            secretKeyRef:
              key: CLOUDFLARE_DNS_RECORDS
              name: dolidock
        {{ end }}
        - name: USE_CLOUDFLARE_DDNS
          value: {{ .Values.dolidock.useCloudflareDDNS | quote }}
        - name: USE_LETSENCRYPT
          value: {{ .Values.dolidock.useLetsEncrypt | quote }}
        - name: POSTFIX_HOSTNAME
          valueFrom:
            secretKeyRef:
              key: POSTFIX_HOSTNAME
              name: dolidock
        - name: POSTFIX_myhostname
          valueFrom:
            secretKeyRef:
              key: POSTFIX_myhostname
              name: dolidock
        - name: POSTFIX_helo_name
          valueFrom:
            secretKeyRef:
              key: POSTFIX_helo_name
              name: dolidock
        {{ if .Values.smtpd.relayHost }}
        - name: RELAYHOST
          value: {{ .Values.smtpd.relayHost | quote }}
        {{ end }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.smtpd.image.repository }}:{{ .Values.smtpd.image.tag | default .Chart.AppVersion }}
        name: smtpd
        ports:
        - containerPort: 25
        resources: {{- toYaml .Values.smtpd.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /var/www/dolidock
          name: {{ if (default .Values.smtpd.useDolidockPVC) }}dolidock-data{{ else }}smtpd-data{{ end }}
      imagePullSecrets: {{ .Values.imagePullSecrets | default list | toJson }}
      restartPolicy: Always
      volumes:
      - name: {{ if (default .Values.smtpd.useDolidockPVC) }}dolidock-data{{ else }}smtpd-data{{ end }}
        persistentVolumeClaim:
          claimName: {{ if (default .Values.smtpd.useDolidockPVC) }}dolidock-data{{ else }}smtpd-data{{ end }}