apiVersion: v1
kind: Service
metadata:
  name: dolidock
  labels:
    io.kompose.service: dolidock
  {{- include "dolidock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dolidock.type }}
  selector:
    io.kompose.service: dolidock
  {{- include "dolidock.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.dolidock.ports | toYaml | nindent 2 -}}