{{ if .Values.crontabui.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crontabui-ingress
  labels:
  {{- include "dolidock.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ required "dolidock.crontabuiHostname is required" .Values.dolidock.crontabuiHostname }}
    http:
      paths:
      - backend:
          service:
            name: 'crontabui'
            port:
              number: 8000
        path: /
        pathType: Prefix
  {{ if .Values.ingress.tls.certIssuer }}
  tls:
  - hosts:
    - {{ .Values.dolidock.crontabuiHostname }}
    secretName: crontabui-ingress-cert
  {{ end }}
{{ end }}