apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dolidock-ingress
  labels:
  {{- include "dolidock.labels" . | nindent 4 }}
  annotations:
    {{ if .Values.ingress.tls.certIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tls.certIssuer }}
    {{ end }}
    {{ if .Values.ingress.annotations -}}
    {{ .Values.ingress.annotations | toYaml | nindent 4}}
    {{ end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ required "dolidock.hostname is required" .Values.dolidock.hostname }}
    http:
      paths:
      - backend:
          service:
            name: 'dolidock'
            port:
              number: 80
        path: /
        pathType: Prefix
  {{ if .Values.ingress.tls.certIssuer }}
  tls:
  - hosts:
    - {{ .Values.dolidock.hostname }}
    secretName: dolidock-ingress-cert
  {{ end }}