apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    io.kompose.service: memcached
  {{- include "dolidock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.memcached.type }}
  selector:
    io.kompose.service: memcached
  {{- include "dolidock.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.memcached.ports | toYaml | nindent 2 -}}