{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data
  labels:
    io.kompose.service: mysql-data
  {{- include "dolidock.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.mysqlData.storageRequest | quote }}
  volumeMode: Filesystem
{{- end }}