apiVersion: v1
kind: Secret
metadata:
  name: dolidock
  labels:
  {{- include "dolidock.labels" . | nindent 4 }}
stringData:
  API_LAYER_KEY: {{ required "dolidock.apiLayerKey is required" .Values.dolidock.apiLayerKey
    | quote }}
  DOLI_ADMIN_LOGIN: {{ required "dolidock.doliAdminLogin is required" .Values.dolidock.doliAdminLogin
    | quote }}
  DOLI_ADMIN_PASSWORD: {{ required "dolidock.doliAdminPassword is required" .Values.dolidock.doliAdminPassword
    | quote }}
  DOLI_DB_NAME: {{ required "dolidock.doliDbName is required" .Values.dolidock.doliDbName
    | quote }}
  DOLI_DB_PASSWORD: {{ required "dolidock.doliDbPassword is required" .Values.dolidock.doliDbPassword
    | quote }}
  DOLI_DB_USER: {{ required "dolidock.doliDbUser is required" .Values.dolidock.doliDbUser
    | quote }}
  MYSQL_DATABASE: {{ required "dolidock.doliDbName is required" .Values.dolidock.doliDbName
    | quote }}
  MYSQL_PASSWORD: {{ required "dolidock.doliDbPassword is required" .Values.dolidock.doliDbPassword
    | quote }}
  MYSQL_ROOT_PASSWORD: {{ required "dolidock.mysqlRootPassword is required" .Values.dolidock.mysqlRootPassword
    | quote }}
  MYSQL_USER: {{ required "dolidock.doliDbUser is required" .Values.dolidock.doliDbUser
    | quote }}
  {{ if .Values.crontabui.enabled }}
  crontabui-password: {{ required "dolidock.crontabuiPassword is required" .Values.dolidock.crontabuiPassword | quote }}
  crontabui-user: {{ required "dolidock.crontabuiUser is required" .Values.dolidock.crontabuiUser | quote }}
  {{ end }}
type: Opaque