apiVersion: v1
kind: Secret
metadata:
  name: dolidock
  labels:
  {{- include "dolidock.labels" . | nindent 4 }}
stringData:
  ALLOWED_SENDER_DOMAINS: {{ required "dolidock.allowedSenderDomains is required"
    .Values.dolidock.allowedSenderDomains | quote }}
  API_LAYER_KEY: {{ required "dolidock.apiLayerKey is required" .Values.dolidock.apiLayerKey
    | quote }}
  {{ if eq .Values.dolidock.useCloudflareDDNS '1' }}
  CLOUDFLARE_API_KEY: {{ required "dolidock.cloudflareApiKey is required" .Values.dolidock.cloudflareApiKey
    | quote }}
  CLOUDFLARE_DNS_RECORDS: {{ required "dolidock.cloudflareDnsRecords is required"
    .Values.dolidock.cloudflareDnsRecords | quote }}
  CLOUDFLARE_ZONE_ID: {{ required "dolidock.cloudflareZoneId is required" .Values.dolidock.cloudflareZoneId
    | quote }}
  {{ end }}
  DKIM_PRIVATE_KEY: {{ required "dolidock.dkimPrivateKey is required" .Values.dolidock.dkimPrivateKey
    | quote }}
  DKIM_SELECTOR: {{ required "dolidock.dkimSelector is required" .Values.dolidock.dkimSelector
    | quote }}
  DOLI_ADMIN_LOGIN: {{ required "dolidock.doliAdminLogin is required" .Values.dolidock.doliAdminLogin
    | quote }}
  DOLI_ADMIN_PASSWORD: {{ required "dolidock.doliAdminPassword is required" .Values.dolidock.doliAdminPassword
    | quote }}
  DOLI_DB_NAME: {{ required "dolidock.doliDbName is required" .Values.dolidock.doliDbName
    | quote }}
  DOLI_DB_PASSWORD: {{ required "dolidock.doliDbPassword is required" .Values.dolidock.doliDbPassword
    | quote }}
  DOLI_DB_USER: {{ required "dolidock.doliDbUser is required" .Values.dolidock.doliDbUser
    | quote }}
  MYSQL_DATABASE: {{ required "dolidock.doliDbName is required" .Values.dolidock.doliDbName
    | quote }}
  MYSQL_PASSWORD: {{ required "dolidock.doliDbPassword is required" .Values.dolidock.doliDbPassword
    | quote }}
  MYSQL_ROOT_PASSWORD: {{ required "dolidock.mysqlRootPassword is required" .Values.dolidock.mysqlRootPassword
    | quote }}
  MYSQL_USER: {{ required "dolidock.doliDbUser is required" .Values.dolidock.doliDbUser
    | quote }}
  POSTFIX_HOSTNAME: {{ required "dolidock.postfixHostname is required" .Values.dolidock.postfixHostname
    | quote }}
  POSTFIX_helo_name: {{ required "dolidock.postfixHostname is required" .Values.dolidock.postfixHostname
    | quote }}
  POSTFIX_myhostname: {{ required "dolidock.postfixHostname is required" .Values.dolidock.postfixHostname
    | quote }}
  {{ if .Values.crontabui.enabled }}
  crontabui-password: {{ required "dolidock.crontabuiPassword is required" .Values.dolidock.crontabuiPassword | quote }}
  crontabui-user: {{ required "dolidock.crontabuiUser is required" .Values.dolidock.crontabuiUser | quote }}
  {{ end }}
type: Opaque