apiVersion: v1
kind: Service
metadata:
  name: dolirate
  labels:
    io.kompose.service: dolirate
  {{- include "dolidock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dolirate.type }}
  selector:
    io.kompose.service: dolirate
  {{- include "dolidock.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.dolirate.ports | toYaml | nindent 2 -}}