apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    io.kompose.service: phpmyadmin
  {{- include "dolidock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.phpmyadmin.type }}
  selector:
    io.kompose.service: phpmyadmin
  {{- include "dolidock.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.phpmyadmin.ports | toYaml | nindent 2 -}}