apiVersion: v1
kind: Service
metadata:
  name: crontabui
  labels:
    io.kompose.service: crontabui
  {{- include "dolidock.labels" . | nindent 4 }}
spec:
  type: {{ .Values.crontabui.type }}
  selector:
    io.kompose.service: crontabui
  {{- include "dolidock.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.crontabui.ports | toYaml | nindent 2 -}}