apiVersion: v1
kind: Service
metadata:
  name: smtpd
  labels:
    io.kompose.service: smtpd
  {{- include "dolidock.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o okteto/k8s.yml
    kompose.version: 1.28.0 (c4137012e)
spec:
  type: {{ .Values.smtpd.type }}
  selector:
    io.kompose.service: smtpd
  {{- include "dolidock.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.smtpd.ports | toYaml | nindent 2 -}}