{{ if (default .Values.smtpd.useDolidockPVC) }}
# if you want to use the datastore from dolidock use
# --set smtpd.useDolidockPVC=true
{{ else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smtpd-data
  labels:
    io.kompose.service: smtpd-data
  {{- include "dolidock.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.smtpdData.storageRequest | quote }}
  volumeMode: Filesystem
{{ end }}