apiVersion: v1
kind: Service
metadata:
  name: .value.service.name
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 25
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-flex-smtpd