loglevel: info
secret:
  id_ed25519: ""
  id_ed25519_pub: ""
image:
  repository:  rustdesk/rustdesk-server-s6
  tag: latest
  pullPolicy: IfNotPresent

hbbs:
  encrypted: "1"
  command: hbbs

hbbr:
  command: hbbr

volume:
  mountPath: /data

persistence:
  enabled: false
  size: 1Gi

ingress:
  enabled: false
  host: example.com
  annotations: {}
  clusterIssuer: "cert-manager"

api:
  image: eltorio/sctgdesk-api-server:v1.4.6
  authkey: "123456789"
  cryptkey: "NanEVhjEwuPSemoJkwcYEcjDJRVWcZfb9bIIZcBeswhPProot"
  s3:
    endpoint: "https://s3.amazonaws.com"
    region: "us-east-1"
    access_key: "access_key"
    secret_key: "secret"
    bucket: "bucket"
    windows64_key: "windows64.exe"
    windows32_key: "windows32.exe"
    osx_key: "osx.dmg"
    osx_arm64_key: "osx_arm64.dmg"
    ios_key: "ios.ipa"
gateway:
  enabled: false
  gatewayClass: haproxy-gatewayclass