apiVersion: v1
kind: Secret
metadata:
  name: smtpd
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "gitea.labels" . | nindent 4 }}
stringData:
  ALLOWED_SENDER_DOMAINS: {{ required "smtpd.allowedSenderDomains is required"
    .Values.smtpd.allowedSenderDomains | quote }}
  {{ if eq .Values.smtpd.useCloudflareDDNS "1" }}
  CLOUDFLARE_API_KEY: {{ required "cloudflareApiKey is required" .Values.smtpd.cloudflareApiKey
    | quote }}
  CLOUDFLARE_DNS_RECORDS: {{ required "smtpd.cloudflareDnsRecords is required"
    .Values.smtpd.cloudflareDnsRecords | quote }}
  CLOUDFLARE_ZONE_ID: {{ required "cloudflareZoneId is required" .Values.smtpd.cloudflareZoneId
    | quote }}
  {{ end }}
  DKIM_PRIVATE_KEY: {{ required "smtpd.dkimPrivateKey is required" .Values.smtpd.dkimPrivateKey
    | quote }}
  DKIM_SELECTOR: {{ required "smtpd.dkimSelector is required" .Values.smtpd.dkimSelector
    | quote }}
  POSTFIX_HOSTNAME: {{ required "smtpd.postfixHostname is required" .Values.smtpd.postfixHostname
    | quote }}
  POSTFIX_helo_name: {{ required "smtpd.postfixHostname is required" .Values.smtpd.postfixHostname
    | quote }}
  POSTFIX_myhostname: {{ required "smtpd.postfixHostname is required" .Values.smtpd.postfixHostname
    | quote }}
type: Opaque