{{ if .Values.getlaserfile.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: getlaserfile-service
spec:
  type: {{ .Values.getlaserfile.service.type | default "ClusterIP" }}
  selector:
    app: getlaserfile
  ports:
    - port: {{ .Values.getlaserfile.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{ end }}