apiVersion: v1
kind: Service
metadata:
  name: smtpd
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.smtpd.type | default "ClusterIP" }}
  selector:
    app: smtpd
  ports:
	{{- .Values.smtpd.ports | toYaml | nindent 2 -}}