
{{ if .Values.gitea.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata: 
    name: gitea-ssh-gateway
    namespace: {{ .Release.Namespace }}
    labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gitea.gateway.gatewayClassName }}
  listeners:
  - name: {{ printf "%s-%s-ssh" .Release.Namespace .Release.Name | trunc 63 }}
    protocol: TCP
    port: {{ .Values.gitea.service.ports.ssh }}
    allowedRoutes:
      kinds:
        - group: gateway.networking.k8s.io
          kind: TCPRoute
      namespaces:
        from: Same
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TCPRoute
metadata:
  name: gitea-ssh-route
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "gitea.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: gitea-ssh-gateway
  rules:
    - backendRefs:
        - kind: Service
          name: {{ include "common.names.fullname" . }}
          port: {{ .Values.gitea.service.ports.ssh }}
{{ end }}